module.exports = {

  CONNECTION: 'connection',
  CONNECTION_ACK: 'SUCCESS_CONNECT',
  CONNECTION_BROADCAST: 'USER_CONNECTED',
  DISCONNECT: 'disconnect',
  DISCONNECT_BROADCAST: 'USER_DISCONNECTED',

  USER_NAME: 'SET_NAME',
  USER_NAME_BROADCAST: 'USER_NAME_UPDATED',
  USER_QUERY: 'USER_LIST_QUERY',
  USER_RESULT: 'USER_LIST_RESULT',

  MESSAGE_CREATE: 'CREATE_MESSAGE',
  MESSAGE_CREATE_BROADCAST: 'NEW_MESSAGE',
  MESSAGE_DELETE: 'DELETE_MESSAGE',
  MESSAGE_DELETE_BROADCAST: 'MESSAGE_DELETED',
  MESSAGE_UPDATE: 'UPDATE_MESSAGE',
  MESSAGE_UPDATE_BROADCAST: 'MESSAGE_UPDATED',

  HISTORY: 'HISTORY'
};
